Subaru-PFS/drp_stella

python/pfs/drp/stella/reduceArcRefSpecTask.py
python/pfs/drp/stella/reduceArcTask.py
tests/testDRP.py

"subprocess.Popen" simply starts the command in the background while
the rest of the script is continued. In contrast to that,
"subprocess.call" waits for the command to complete and returns the
"returncode" attribute which we need to check to see if our test
was successful.

tests/testDRP.py: replace Popen with call to check the return value

---

examples/overplotFiberTraceCenter.py
src/FiberTraces.cc
src/Spectra.cc
src/math/CurveFitting.cc
tests/FiberTraces.py
tests/Spectra.py

Also fixed some typos and moved the context information out of the
log messages (as it's in the logger)

Use . not :: as a separator in loggers

---

python/pfs/drp/stella/spectraContinued.py
tests/test_Spectrum.py

This involves a bit of refactoring of Spectrum.plot so they can share
code. Renamed the plotBackground and plotReferenceLines kwargs to
doBackground and doReferenceLines.
SpectrumSet.plot doesn't have all the features that Spectrum.plot does,
as I decided that plotting the background and reference lines would just
make the plots too confusing.

PIPE2D-296: Add SpectrumSet.plot method

---

python/pfs/drp/stella/reduceArcTask.py

HgAr has many many lines below the old default value, so that reduceArc
fails on HgAr arcs without a configuration override. Ne arcs don't care
whether it's 0 or 100, so set it so that both are satisfied.

PIPE2D-375: reduceArc: set minArcLineIntensity default to 0

---

python/pfs/drp/stella/SpectrumSetContinued.py

The butler gives us a temporary filename that we're supposed to
write to, and then it moves it to the correct place. We were
writing to the correct place, and then the empty temporary file
was being written over the top. Instead, write to the filename
we're given.

PIPE2D-411: fix pfsArm writing under reduceArc

---

python/pfs/drp/stella/fitFocalPlane.py
python/pfs/drp/stella/subtractSky1d.py

Changed open(..., "w") to open(..., "wb") for files that FITS data are
written on. Not only is it logically wrong to use the text mode here,
but it is also forbidden in astropy 3.2.

DAMD-61: changed file mode "w" to "wb"

---

python/pfs/drp/stella/constructFiberFlatTask.py
python/pfs/drp/stella/constructFiberTraceTask.py

The hexapod position along the slit is now called 'dither' instead
of 'slitOffset'. slitOffset hasn't been set to actual values since
the camera stopped writing W_FCA_DITHER. dither gets its values
from a new header keyword.

PIPE2D-425: use dither instead of slitOffset from butler

---

python/pfs/drp/stella/__init__.py
python/pfs/drp/stella/lsf.py
tests/test_lsf.py

Lsf is an abstract base class based on LSST's Psf class, but
brought down to one dimension.
This includes a Kernel class (for convolving by your Lsf, or
inserting the Lsf at a particular point in the spectrum) and
a couple of basic concrete Lsf classes for demonstration.

PIPE2D-342: add definition of Lsf

---

python/pfs/drp/stella/bootstrap.py

Added log message to indicate which lamps are on for the data in question.

PIPE2D-536: Correct header info for ReduceArc and BootstrapDetectorMap

---

python/pfs/drp/stella/coaddSpectra.py
python/pfs/drp/stella/constructFiberTraceTask.py
python/pfs/drp/stella/constructSpectralCalibs.py
python/pfs/drp/stella/datamodel/interpolate.py
python/pfs/drp/stella/datamodel/pfsFiberArray.py
python/pfs/drp/stella/measureFluxCalibration.py
tests/test_FluxTable.py

I also fixed some interpolation problems I noticed.

PIPE2D-541: Prevent constructFiberTrace from operating on different fiber configurations

---

python/pfs/drp/stella/DetectorMapContinued.py
python/pfs/drp/stella/bootstrap.py
python/pfs/drp/stella/buildFiberProfiles.py
python/pfs/drp/stella/centroidLines.py
python/pfs/drp/stella/measureSlitOffsets.py
python/pfs/drp/stella/reduceArc.py

Please use afwDisplay.setDefaultBackend() instead

PIPE2D-746: Remove all explicit mention of afwDisplay backend

---

python/pfs/drp/stella/synthetic.py

A GuideStars instance (or None) now needs to be passed to the
PfsDesign and PfsConfig constructors.

DAMD-101: Save the outputs of shuffle

---

python/pfs/drp/stella/mergeArms.py

I decided to go with only adding the option to mergeArms

PIPE2D-810: Allow the user to specify a pfsConfig file to be used by mergeArms

---

python/pfs/drp/stella/SpectrumSetContinued.py

PIPE2D-868: SpectrumSet.makeImage asserts len(self) == len(fiberTraces) which fails with broken fibres

---

python/pfs/drp/stella/fitBroadbandSED.py
tests/test_fitBroadbandSED.py
ups/drp_stella.table

The broadband photometry table is now included in `fluxmodeldata`
package together with the synthetic spectra from which the b.b.
photometries derive.

PIPE2D-920: Change location of broadband photometry table for FitBroadbandSEDTask

---

python/pfs/drp/stella/utils/display.py

pfsConfig.selectFiber() returns a scalar int value if the input argument
is also a scalar. This is how it is used in showDetectorMap.

PIPE2D-967: showDetectorMap - fix call to pfsConfig.selectFiber()

---

python/pfs/drp/stella/fitPfsFluxReference.py
python/pfs/drp/stella/fitReference.py

fitPfsFluxReference.py is intended to be a subtask of flux calibration.
It does the task previously under the charge of fitReference.py.
This subtask runs, but is not in its final state.
To be specific, more lines of code in relation to galactic extinction must be added.
This branch requires obs_pfs/tickets/PIPE2D-922.

PIPE2D-922: Add fitPfsFluxReference.py

---

python/pfs/drp/stella/fitPfsFluxReference.py

Several imported modules were not used, which broke the unit tests.

PIPE2D-1005: Fix test breakage introduced by PIPE2D-922

---

python/pfs/drp/stella/fitPfsFluxReference.py

Radial velocities are required by the subsequent task,
and they have to be stored in PfsFluxReference objects.

PIPE2D-1014: Store radial velocities in PfsFluxReference objects

---

python/pfs/drp/stella/dustMap.py
python/pfs/drp/stella/extinctionCurve.py
python/pfs/drp/stella/fitPfsFluxReference.py
tests/test_dustMap.py
tests/test_extinctionCurve.py
tests/test_fitPfsFluxReference.py
ups/drp_stella.table

fitPfsFluxReference now considers Galactic extinction. `DustMap` and `F99ExtinctionCurve` classes are also introduced by this branch. No scientific quality is tested in the unit test of fitPfsFluxReference, for its output is too bad to pass any tests (PIPE2D-1012)

PIPE2D-987: Make fitPfsFluxReference consider Galactic extinction

---

bin.src/fitPfsFluxReference.py
python/pfs/drp/stella/fitPfsFluxReference.py

FitPfsFluxReferenceTask is now executable, and its output is written to a file.
This branch requires `tickets/PIPE2D-1021` branch of `obs_pfs`.

PIPE2D-1021: Make FitPfsFluxReferenceTask executable

---

python/pfs/drp/stella/fitPfsFluxReference.py
tests/test_fitPfsFluxReference.py

The essential change is lines 362-366. Most of the other changes are required because I use the division operator of the extended PfsMerged class. I take this opportunity and use the division operator also at lines 403-405, though this change might be irrelevant here.

PIPE2D-1026: fitPfsFluxReference.py: Take `PfsMerged.norm` into account

---

python/pfs/drp/stella/makeFluxModelInterpolator.py

The full fluxmodeldata package consists of the spectra in the small package, and of many pre-interpolated spectra. To make the interpolator from the full package, `makeFluxModelInterpolator.py` must choose only those spectra that are in the small package, which are not the product of the pre-interpolation. And `makeFluxModelInterpolator.py` must use the same hyperparameters as used in the pre-interpolation.
I don't recommend to set up the full fluxmodeldata package during developments because `scons tests` will come to take a few hours.

PIPE2D-1053: makeFluxModelInterpolator.py: Changes for full fluxmodeldata package

---

python/pfs/drp/stella/fitPfsFluxReference.py
tests/test_fitPfsFluxReference.py

The mask array of a PfsMerged object read from a file is of uint32 type, and longer integers sometimes have to be shortened when operating on the mask array. Because numpy won't implicitly shorten integers by default, we must cast the integers to uint32 explicitly.

PIPE2D-1056: fitPfsFluxReference.py: explicitly shorten integer type to avoid exceptions

---

python/pfs/drp/stella/fitPfsFluxReference.py
python/pfs/drp/stella/fluxModelInterpolator.py
python/pfs/drp/stella/fluxModelSet.py

LSF convolution must at all costs be done before whitening because the convolution lowers the continuum due to dense absorption lines. Because the density of the absorption lines varies from place to place, the result of LSF convolution after whitening is not even horizontal. These commits makes the two operations take place in the correct order.

PIPE2D-1065: fitPfsFluxReference.py: LSF convolution before whitening

---

python/pfs/drp/stella/utils/display.py

Otherwise, this warning is raised any time any drp_stella module is loaded.

PIPE2D-1074: Limit display_matplotlib/addPfsCursor to function only.

---

python/pfs/drp/stella/fitPfsFluxReference.py

Fixed a typo (`filterId` -> `fiberId`),
which is the direct cause of this bug.
Also, "ABSENT_FIBER" condition is now checked earlier. This condition (`pfsConfig.fiberId` is not in `pfsMerged.fiberId`) holds more often than I thought. Checking it early saves unnecessary computations.

PIPE2D-1105: Fix: PfsFluxReference has invalid spectra with flag=0

---

python/pfs/drp/stella/estimateRadialVelocity.py
python/pfs/drp/stella/fitFluxCal.py
python/pfs/drp/stella/fitPfsFluxReference.py
python/pfs/drp/stella/utils/debugging.py

Among the requested debug products, `flux_scaling_chi2` is always put to the pfsFluxReference object because it can be useful to `fitFluxCal.py`. The other debug products are output to the current working directory when requested.

PIPE2D-1113: fitPfsFluxReference: Add debug outputs

---

python/pfs/drp/stella/fitBroadbandSED.py
python/pfs/drp/stella/fitReference.py
tests/test_fitBroadbandSED.py
tests/test_fitPfsFluxReference.py

The integration test and the weekly test will be broken after this change. To fix this problem, run
`PIPE2D-1110-change-filter-names.py`.
There is a link to this file in PIPE2D-1110, JIRA.

PIPE2D-1110: Change filter names

---

python/pfs/drp/stella/fitFluxCal.py
python/pfs/drp/stella/fluxCalibrate.py

`fluxCalibrate.py` and `fitFluxCal.py` are fixed. In addition to the fix, code is copied from `fluxCalibrate.py` to `fitFluxCal.py` again.

PIPE2D-1130: Fix mismatch of sizes of lists passed to FluxTableTask.run()

---

python/pfs/drp/stella/estimateRadialVelocity.py
python/pfs/drp/stella/fitPfsFluxReference.py
tests/test_estimateRadialVelocity.py
tests/test_fitBroadbandSED.py
tests/test_fitPfsFluxReference.py

Previously, we found the peak position of the cross correlation function
by fitting a Gaussian to the c.c.f. Because exceptions were sometimes
raised by the optimizer, we change the peak-finding method to quadratic
interpolation. Because radial velocities found by the latter method
have large variance when `searchStep` is small, we change it from 5 km/s
to 10 km/s (This step should not be wider than the smallest possible
LSF). In addition, we lower S/N used in the unit test according to
true observed spectra.

PIPE2D-1147: estimateRadialVelocity: Change `findMethod` to "quadratic"

---

python/pfs/drp/stella/fitPfsFluxReference.py

We raise the cut-off threshold (If the prior probability of a flux model is less than the threshold, its posterior probability is forced to be 0) so that less flux models have to be read from file and fitted a continuum to. In addition, we postpone reading flux models until they are actually required.

PIPE2D-1145: Make fitPfsFluxReference.py faster

---

pipelines/science2.yaml
python/pfs/drp/stella/fitFluxCal.py
python/pfs/drp/stella/fitPfsFluxReference.py

Added the elements necessary for `FitPfsFluxReferenceTask` and `FitFluxCalTask` to be compatible with Gen3 butler.

PIPE2D-1149: Make fitPfsFluxReference & fitFluxCal compatible with Gen3 butler

---

python/pfs/drp/stella/reduceExposure.py

It's helpful to always have detectorMap_used available, regardless of the configuration used.

PIPE2D-1159: Please always provide a detectorMap_used file

---

python/pfs/drp/stella/fitBroadbandSED.py
python/pfs/drp/stella/fitPfsFluxReference.py
python/pfs/drp/stella/fluxModelSet.py
tests/test_fitBroadbandSED.py
tests/test_fluxModelSet.py

This pull request contains three main changes:
1. Pack model templates into one uncompressed zip file.
2. Downsample model templates before continuum fitting.
With these two changes, fitPfsFluxReference in the integration test will run in less than 1 hour/visit/core with "full" model set.
3. Remove the filter name conversion table from FitBroadbandSEDTask.
This change will make the class simpler, though it will break compatibility to old fluxmodeldata packages. Users must install the new versions available at https://hscdata.mtk.nao.ac.jp/hsc_bin_dist/pfs/fluxmodeldata-ambre-20230428-small.tar.xz and https://hscdata.mtk.nao.ac.jp/hsc_bin_dist/pfs/fluxmodeldata-ambre-20230428-full.tar.xz .

PIPE2D-1208: Make fitPfsFluxReference even faster

---

python/pfs/drp/stella/fluxModelInterpolator.py
python/pfs/drp/stella/makeFluxModelInterpolator.py

fluxModelInterpolator.py after this commit requires fluxmodeldata-ambre-20230602.

PIPE2D-1231: fluxModelInterpolator: Use PCA to reduce memory usage

---

python/pfs/drp/stella/synthetic.py
tests/test_FitFocalPlaneTask.py
tests/test_fitBroadbandSED.py
tests/test_fitPfsFluxReference.py

I created a relevant changes for datamodel (DAMD-137). I ran scons with the following setup. I don't see errors related to PfsDesign/PfsConfig, but there are some errors in the log. 
```
source /work/stack/loadLSST.zsh
setup pfs_pipe2d w.2023.29
setup -jr .  # at datamodel and drp_stella
scons 2>&1 | tee scons_DAMD-137-003.log
```
[scons_DAMD-137-003.log](https://github.com/Subaru-PFS/drp_stella/files/12075283/scons_DAMD-137-003.log)

feat: add epch/pmRa/pmDec/parallax to PfsDesign/PfsConfig (DAMD-137)

---

python/pfs/drp/stella/fitContinuum.py

binData() is one of the hot spots during the execution of
fitPfsFluxReference.py. It can be made faster by removing the for-loop.
Binning results may slightly change due to the difference regarding
the treatment of the case when `numBins` does not divide `len(xx)`.

PIPE2D-1259: fitContinuum.py: Make binData() faster

---

pipelines/science.yaml
python/pfs/drp/stella/fitBroadbandSED.py
python/pfs/drp/stella/fitPfsFluxReference.py
tests/test_fitBroadbandSED.py

If the guessed parameter of a spectrum is out of the parameter domain
of the models we have prepared, we should discard the spectrum.

PIPE2D-1237: fitPfsFluxReference: Discard FLUXSTD when its param is out of range

---

python/pfs/drp/stella/lsf.py
python/pfs/drp/stella/reduceProfiles.py
src/FiberTraceSet.cc

reduceExposure was previously updated to operate on a single exposure at a time rather than lists. It seems there weren't corresponding changes in reduceProfiles.

PIPE2D-1301: reduceProfiles: update following reduceExposure API change

---

python/pfs/drp/stella/reduceExposure.py

The document of ReduceExposureConfig.gaussianLsfWidth says its elements are Gaussian sigmas, but the values actually written there were FWHM.

PIPE2D-1252: reduceExposure: Correct LSF widths to Gaussian sigmas.

---

python/pfs/drp/stella/fitFluxCal.py

It was found that integrations of calibrated flux standards did not agree with broad-band fluxes. Calibration vectors proved to be wrong because of misuse of PfsFiberArraySet's *= operator.

PIPE2D-1361: Fix: fitFluxCal.py: calibration vectors are wrong.

---

python/pfs/drp/stella/datamodel/pfsFiberArray.py
python/pfs/drp/stella/fitFluxCal.py
python/pfs/drp/stella/fitReference.py
python/pfs/drp/stella/focalPlaneFunction.py
python/pfs/drp/stella/utils/polynomialND.py
tests/test_polynomialND.py

The type of fluxCal is no longer ConstantFocalPlaneFunction but another
subclass of FocalPlaneFunction. It consists of (1) an average flux
calibration vector up to scales and (2) the exponential of a polynomial
of (x, y, lambda), which is expected to be a gently varying function
of fiber position and wavelength, representing scale (i.e. overall
height of a flux calibration vector) that vary according to fiber
position in the field of view, and seeing variation according to
wavelength.

PIPE2D-1362: fitFluxCal should correct seeing variation

---

python/pfs/drp/stella/fitPfsFluxReference.py
tests/test_fitPfsFluxReference.py

In fitting a flux reference, we use different wavelength ranges for mid-res spectra and low-res spectra. Whether spectra are mid-res or low-res is determined not by pfsConfig but by the spectra themselves because pfsConfig's information is unreliable: pfsConfig.arms may be "brn" when it should be "bmn". The reason for this is that humans may disobey pfsDesign in actual observation.

PIPE2D-1446: fitPfsFluxReference: Use diff. w.l.ranges for mid- and low-res spectra

---

python/pfs/drp/stella/fitFluxCal.py
python/pfs/drp/stella/fitPfsFluxReference.py
python/pfs/drp/stella/fitReference.py
tests/test_fitReference.py

The denominators of chi^2 for comparing an observed spectrum with
broadband fluxes were the errors of broadband fluxes, the error of
the observed spectrum ignored. The error of the observed spectrum
is now taken into account.
This PR also includes two unrelated changes: (1) Output best-fit models (if such setting is described in `debug.py`) (2) Prevent fitFluxCal.py from outputting objective values for every loop.

PIPE2D-1558: fitFluxCal: Take spectrum's error into account during fitting

---

python/pfs/drp/stella/fitFluxCal.py
python/pfs/drp/stella/fitPfsFluxReference.py

Previously, only PS1 was available as the source of flux standards.
It was because we interpolate in a complicated way those parts of
spectra that are missing due to absent arms. This interpolation
routine was valid only with PS1 fluxes. We now accept flux standards
from HSC and Gaia by extending the interpolation routine.
This PR includes several commits to make the above change possible.

PIPE2D-1596: fitFluxCal: Accept flux standards from HSC and Gaia

---

pipelines/fiberNorms.yaml
pipelines/reduceExposure.yaml
python/pfs/drp/stella/calculateReferenceFlux.py

I think that calculateReferenceFlux.py is dead, but until it's removed it's less confusing to fix it

Tickets/pipe2d-1615: Minor Gen3 simplifications/cleanups

---

python/pfs/drp/stella/estimateRadialVelocity.py
python/pfs/drp/stella/fitFluxCal.py
python/pfs/drp/stella/fitPfsFluxReference.py

Flux standards whose S/N are extremely low should not be used even if their flags are clear.

PIPE2D-1592: fitPfsFluxReference: Don't use low-SNR flux standards

---

python/pfs/drp/stella/fitFluxCal.py

We no longer ignore y-band fluxes because n-arm has become available. We lower polynomial order because fitFluxCal takes too much time.

PIPE2D-1711: Change default parameters of fitFluxCal

---

python/pfs/drp/stella/fitFluxCal.py
python/pfs/drp/stella/fitFluxReference.py

J-band flux included in the broad-band flux set would be useful
because it would limit the IR-end of the flux calibration vector.
We fabricate a narrow-J-band flux, guessing it from fluxes of
the other bands.

PIPE2D-1594: fitFluxCal.py: Fabricate narrow-J-band flux
