Subaru-PFS/drp_stella

- python/pfs/drp/stella/reduceArcRefSpecTask.py
- python/pfs/drp/stella/reduceArcTask.py
- python/pfs/drp/stella/utils.py
- tests/Spectra.py
and writePfsArm,
include these functions in reduceArc(RefSpec)Task.py
> Add functions to read WavelengthFile, LineListFile, ReferenceSpectrum

- include/pfs/drp/stella/Controls.h
- include/pfs/drp/stella/DetectorMap.h
- include/pfs/drp/stella/DetectorMapIO.h
- include/pfs/drp/stella/Spectra.h
- python/pfs/drp/stella/calibrateWavelengthsTask.py
- python/pfs/drp/stella/constructFiberTraceTask.py
- python/pfs/drp/stella/detectorMap.cc
- python/pfs/drp/stella/extractSpectraTask.py
- python/pfs/drp/stella/fitContinuum.py
- python/pfs/drp/stella/identifyLines.py
- python/pfs/drp/stella/reduceArcTask.py
- python/pfs/drp/stella/reduceExposure.py
- python/pfs/drp/stella/spectra.cc
- python/pfs/drp/stella/utils.py
- src/DetectorMap.cc
- src/Spectra.cc
- tests/test_DetectorMap.py
> PIPE2D-277: Continuum subtract arc spectra in 2-d

- ups/drp_stella.table
Remove ones we don't need, and add ones we do.
> PIPE2D-292: Strip down dependency tree

- bin.src/makeLamDesign.py
Makes a PfsConfig for a LAM exposure, given the colors of the fibers
used.
> PIPE2D-338: add makeLamConfig.py

- python/pfs/drp/stella/reduceExposure.py
We have low count levels compared to imaging, so we sometimes have
pixels that are negative after bias+dark, which means the variance
gets set to a negative number, which causes problems downstream
(e.g., CurveFitting.cc:330). Find these pixels, set the variance
to infinity and mask them as BAD.
> PIPE2D-427: reduceExposure: mask negative variance pixels

- python/pfs/drp/stella/constructFiberFlatTask.py
from mask planes leaking through the flat.
> PIPE2D-440: fix holes in fiberTrace

- python/pfs/drp/stella/calibrateWavelengthsTask.py
- python/pfs/drp/stella/reduceArcTask.py
- tests/test_WavelengthFitData.py
- tests/test_tasks.py
A new class, WavelengthFitData, saves the wavelength fit data
(centroid in pixels, fit wavelength, actual wavelength) for
calculating statistics and for later QA.
> PIPE2D-380: save wavelength fit data

- python/pfs/drp/stella/synthetic.py
and photometry errors fiberFluxErr, psfFluxErr, totalFluxErr
> Updated synthetic config generation code with psfFlux, totalFlux

- python/pfs/drp/stella/synthetic.py
New keyword specifying the arms exposed is introduced.
> Updated synthetic psfConfig generation to accommodate arms information.

- include/pfs/drp/stella/FiberTrace.h
- python/pfs/drp/stella/FiberTrace.cc
- python/pfs/drp/stella/bootstrap.py
- python/pfs/drp/stella/fiberProfile.py
- python/pfs/drp/stella/identifyLines.py
- src/FiberTrace.cc
> PIPE2D-853: Fix bootstrap following rename of guessedIntensity

- python/pfs/drp/stella/fitBroadbandSED.py
- tests/test_fitBroadbandSED.py
FitBroadbandSEDTask is a task to derive a probability distribution
function from broad-band SED fitting of a standard star.
The original program was provided by Takuji Yamashita.
Requires PIPE2D-852 upgrade to drp_pfs_data.
> PIPE2D-852: Added fitBroadbandSED.py

- python/pfs/drp/stella/estimateRadialVelocity.py
- tests/test_estimateRadialVelocity.py
This is supposed to be a subtask of flux calibration
being worked on by Takuji Yamashita.
> PIPE2D-871: Add EstimateRadialVelocityTask

- python/pfs/drp/stella/fitBroadbandSED.py
- python/pfs/drp/stella/fluxModelSet.py
- tests/test_fluxModelSet.py
FluxModelSet is a class that helps to deal with spectra
in fluxmodeldata package.
> PIPE2D-921: Add class FluxModelSet

- python/pfs/drp/stella/subtractSky2d.py
Otherwise processing may fail if there is a mis-match.
> PIPE2D-993: Use only common fibers from pfsConfig, FiberTraceSet and apCorr

- bin.src/fitFluxCal.py
- python/pfs/drp/stella/fitFluxCal.py
This executable makes "fluxCal" from "pfsFluxReference",
just like fluxCalibrate.py makes "fluxCal" from "pfsReference".
> PIPE2D-1013: Add fitFluxCal.py

- python/pfs/drp/stella/fitPfsFluxReference.py
- tests/test_fitPfsFluxReference.py
Previously, we did not use `pfsMergedLsf` but used a Gaussian LSF tentatively. This change replaces the tentative code with `pfsMergedLsf`.
> PIPE2D-1027: fitPfsFluxReference.py: Use pfsMergedLsf

- python/pfs/drp/stella/fitPfsFluxReference.py
Number of required broadband fluxes for a FLUXSTD spectrum
to be fitted to is now configurable.
With `--config minBroadbandFluxes=1`, `fitPfsFluxReference.py`
gets able to fit a model to a FLUXSTD spectrum with only a single
broadband flux in PfsConfig.
> PIPE2D-1029: fitPfsFluxReference.py: Add option not to skip spectra with single b.b.flux

- python/pfs/drp/stella/__init__.py
> Add IPC mask plane for H4RGs

- python/pfs/drp/stella/fitFluxCal.py
Fibers of these targetTypes have (ra, dec) = (nan, nan) in PfsConfig. This is appropriate because these fibers do not point to the sky. But the coordinates being NaN causes an exception during the process of making PfsSingle, for NaN is not allowed in FITS headers.
> PIPE2D-1106: Don't make PfsSingle for UNASSIGNED or ENGINEERING targets

- python/pfs/drp/stella/fitPfsFluxReference.py
Uninteresting regions in observed spectra must be masked in radial velocity estimation in the same way as they are in spectral typing.
> PIPE2D-1109: fitPfsFluxReference.py: Mask some regions in estimating radial velocity

- python/pfs/drp/stella/fitBroadbandSED.py
- python/pfs/drp/stella/fitPfsFluxReference.py
- python/pfs/drp/stella/utils/math.py
Added debug option (doWriteChisq) to output chi^2. With doWriteWhitenedFlux option, whitened model flux is also written together with observed flux.
I had to make somewhat many changes: To output degree of freedom with chi^2, I had to make a special class ChisqList. To reproduce the best-fit model as it was when it was compared to the observed flux, I had to make dopplerShift() function.
> PIPE2D-1182: fitPfsFluxReference: More debug outputs

- python/pfs/drp/stella/fitPfsFluxReference.py
Previously, fitPfsFluxReference fitted models to spectra by evaluating
chi^2 for every precomputed model template. After this change,
fitPfsFluxReference uses Powell's method (by default) to fit models.
With this change, fitPfsFluxReference.py runs 3x faster (if the number
of FLUXSTD in a visit is 100). The quality of the output seems slightly
better nonetheless for the possibility of falling into a local minimum,
to my surprise. It may be that the sub-grid peak finder in the previous
method was bad, or that LSF approximation for speedup was problematic,
though these are mere guesses.
The previous method can be restored with
`config.minimizationMethod='brute-force'`.
> PIPE2D-1238: fitPfsFluxReference: Fit models using Powell's method

- python/pfs/drp/stella/fitPfsFluxReference.py
- python/pfs/drp/stella/fluxModelInterpolator.py
I want to put two changes into the master branch.
These changes will save us 1000 seconds out of 4676 seconds to run
fitPfsFluxReference on a visit.
- Don't resample models twice
- Use fewer PCA components
> PIPE2D-1279: Make fitPfsFluxReference faster (3rd)

- python/pfs/drp/stella/synthetic.py
- tests/test_FitFocalPlaneTask.py
- tests/test_fitBroadbandSED.py
- tests/test_fitPfsFluxReference.py
Similar to PR#329, add `proposalId` and `obCode`.
> DAMD-146: add proposalId and obCode to pfsDesign/pfsConfig files

- python/pfs/drp/stella/apertureCorrections.py
A cleverer way would be to build an apCorr object full of NaNs, but I don't know how to do that.
N.b.  Other recovery strategies are possible, but this is simple. We need to label the line fluxes as bad, but it would be nice to keep the raw fluxes too
> Handle failed aperture corrections by setting fluxes to NaN

- python/pfs/drp/stella/fitPfsFluxReference.py
We make a 4D (Teff, log(g), metal, alpha) PDF from broad-band fitting, and use it as the prior in spectrum fitting. It has turned out that its interpolator is one of bottlenecks. Because only Teff can be determined by broad-band fitting, we can marginalize other dimensions to get a 1D prior. 1D interpolators are much faster than 4D ones.
> PIPE2D-1332: fitPfsFluxReference: Use a 1D prior instead of 4D one

- python/pfs/drp/stella/fitFluxCal.py
Amplitudes of observed flux standard are so different from each other that calib vectors (observed flux standard) / (flux reference) vary from each other too much for a clipped mean to be computed. We adjust the heights of calib vectors to each other beforehand to deal with this problem.
> PIPE2D-1336: fitFluxCal: Adjust calib vectors to each other

- python/pfs/drp/stella/constructFiberProfilesTask.py
- python/pfs/drp/stella/extractSpectraTask.py
- python/pfs/drp/stella/fiberProfileSet.py
- python/pfs/drp/stella/readLineList.py
- python/pfs/drp/stella/reduceExposure.py
- python/pfs/drp/stella/utils/display.py
- python/pfs/drp/stella/utils/quality.py
- python/pfs/drp/stella/utils/stability.py
- python/pfs/drp/stella/utils/sysUtils.py
Fixed now, I think.  But note comment on ticket on the need to specify a subset of fibres to extract
> Tickets/pipe2d-1300  Add option --doBoxcarExtraction to reduceExposure.py

- python/pfs/drp/stella/reduceExposure.py
Use boxcar extractions for IIS fibres when we detect that they are illuminated
Actually there are two options to control this; doDetectIIS and doBoxcarForIIS which are both True by default.  You might want to set boxcarWidth too; it has no effect unless doBoxcarExtraction is True (or this code fires)
> Use boxcar extractions for IIS fibres when we detect that they are illuminated

- python/pfs/drp/stella/fitFluxCal.py
If an arm is absent, spectrum in its wavelength range is not available. Because we compare broadband fluxes with integrations of spectra, sampling points absent from the integration ranges lead to erroneous chi^2.
To address this problem, we throw away broadband fluxes if the bands are hardly covered by the observed spectra. In addition, we interpolate or extrapolate the observed spectra so that they will cover entire bands of broadband filters.
> PIPE2D-1427: fitFluxCal.py: Address problems arising from absent arms.

- python/pfs/drp/stella/screen.py
The code handles mixed IIS/PFI fibres, but we also check for all-ENGINEERING in order to generate better log messages
> Don't apply screen corrections to IIS fibres

- python/pfs/drp/stella/fitFluxCal.py
We have fit a polynomial dependent on (x, y, \lambda) to the flux
calibration vector (observed flux / model flux). But the dependence
on \lambda makes calibration vector quite wrong at the red end of
spectra. We therefore use a wavelength-independent polynomial
instead. (In fact, the polynomial is a modification factor by which
to multiply the raw calibration vector. The flux calibration vector
remains wavelength-dependent.)
This pull request includes another commit: "Use L1 loss when robust=True".
It is added here according to a comment on JIRA.
> PIPE2D-1463: fitFluxCal: Use wavelength-independent polynomial

- python/pfs/drp/stella/mergeArms.py
> tickets/PIPE2D-1542 Added fiberNormsVisit

- python/pfs/drp/stella/fitFluxCal.py
We apply a median filter to the spectra of flux standards before integrating them (to compute broadband fluxes) so that outlier pixels in low S/N spectra will not corrupt the integrals.
> fitFluxCal: Apply median filter to spectra before integrating them

- python/pfs/drp/stella/fitFluxCal.py
This is a collection of several improvements to flux calibration.
> PIPE2D-1518: Fix flux normalization variation in flux calibration

- python/pfs/drp/stella/utils/guiders.py
This import changed was missed in PIPE2D-1717.
> Fix refactored import for AutoGuiderStarMask - tickets/PIPE2D-1738

- pipelines/reduceExposure.yaml
Changed `h4_doCR` to `False` in reduceExposure.yaml
> Change h4_doCR to False as default

- python/pfs/drp/stella/barycentricCorrection.py
* To be merged after https://github.com/Subaru-PFS/pfs_utils/pull/82 (https://pfspipe.ipmu.jp/jira/browse/INSTRM-2623)
> Use SUBARU.location from pfs_utils - tickets/PIPE2D-1750
